spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name=com: mysql.jdbc.Driver
    url: jdbc:mysql://192.168.90.25:3306/peoplemanage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
