srping:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.90.25:3306/peoplemanage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

